branding:
  branding_enabled:
    default: false
    client: true
  brand_name:
    default: 'Discourse'
    client: true
  brand_logo_url:
    default: '/images/d-logo-sketch.png'
    client: true
  brand_url:
    default: '/'
    client: true
